# Generated by Django 4.1 on 2023-09-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="subscriptionStatus",
            fields=[
                (
                    "customer_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("customer_email", models.EmailField(max_length=254, unique=True)),
                ("is_subscibed", models.BooleanField(default=False)),
            ],
        ),
    ]
