# Generated by Django 4.1 on 2023-09-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Companies",
            fields=[
                ("company_id", models.IntegerField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=50)),
                ("company_category", models.CharField(max_length=20)),
                ("company_origin", models.CharField(max_length=20)),
                ("company_size", models.IntegerField()),
                ("company_logo", models.URLField(blank=True)),
                ("founded_on", models.DateField()),
            ],
        ),
    ]
